### ISSUE TITLE
Failed to exec findmnt 

### ISSUE THREAD

**Issue by thePanz** [fgrehm/vagrant-lxc#454] opened 2018-02-01 10:27 UTC
After upgrading to vagrant-lxc `1.0.3` I started gettin the following error during `vagrant halt`:

```
DEBUG subprocess: stderr: lxc-attach: attach.c: lxc_attach_run_command: 1292 No such file or directory - Failed to exec "findmnt -R /tmp -o TARGET --list --noheadings | xargs -L 1 --no-run-if-empty umount".
```

`lxc-start --version` : `2.0.8`
`vagrant version` : `2.0.2`
os: ArchLinux 
`findmnt --version` : `findmnt from util-linux 2.31.1`

**Comment by hsoft** [comment] 2018-02-01 11:33
Thanks for the report. I'm wondering what file it is referring to. `/tmp`? Would it be that you don't have a `/tmp` directory in your guest OS at halt time?

**Comment by ccope** [comment] 2018-02-01 11:46
sounds like it can't find the findmnt executable. are you running a container that doesn't have the util-linux package installed?

**Comment by hsoft** [comment] 2018-02-01 11:59
Oh, @thePanz archlinux is the host or the guest? The `findfmt` version you gave is for the host or the guest?

**Comment by thePanz** [comment] 2018-02-01 12:41
ArchLinux is the host.

The Guest is a `debian` VM, and `findmnt from util-linux 2.25.2` is the findmnt version.
The `/tmp` folder exists in the guest machine

**Comment by thePanz** [comment] 2018-02-01 15:27
Is there anything I can provide to spot the issue?

**Comment by ccope** [comment] 2018-02-01 23:13
This and #455 are probably because the commands are not given the full path. Manually running the lxc-attach commands as-is on my own machine works, so I'm guessing somewhere in the codebase the PATH environment variable is being stripped. Either specifying the full binary paths or fixing the PATH variable should work.

**Comment by hsoft** [comment] 2018-02-02 00:19
@ccope good idea, it might very well be this. as for #445, it's the `rm` call that fails, I doubt that it's the same problem.

In any case, I'll wrap those call so that they generate warnings instead of errors. After all, not being able to clear `/tmp` isn't the end of the world...

**Comment by ccope** [comment] 2018-02-02 00:27
If PATH is empty, it wouldn't be able to find rm either (rm is /bin/rm)

**Comment by hsoft** [comment] 2018-02-02 00:29
But it would fail on the first command rather than the second, no?

**Comment by hsoft** [comment] 2018-02-02 01:27
When I try to set `PATH=` in `/etc/environment`, it makes the shell completely broken and I don't get the same error when doing `vagrant halt`. @thePanz I think we'll need a bit more info. Running `vagrant --debug halt` might give something interesting. Also, what happens if you `vagrant ssh` and then run the line in the error message (`findmnt -R /tmp -o TARGET --list --noheadings | xargs -L 1 --no-run-if-empty umount`) as `root`?

**Comment by thePanz** [comment] 2018-02-02 08:02
Thanks @hsoft and @ccope for your support :)
Here https://pastebin.com/kZ7FC2kK the `vagrant --debug halt` fragment of the failure

The second command is successful, no errors are reported:

```
root@solarium:~# findmnt -R /tmp -o TARGET --list --noheadings | xargs -L 1 --no-run-if-empty umount
```

**Comment by ccope** [comment] 2018-02-02 10:16
re: rm failing, you're right, findmnt also should have failed first. I'll post my new theory on the other issue.

**Comment by thePanz** [comment] 2018-02-02 10:39
I run `vagrant lxc sudoers` and the command `vagrant halt` started to work.
But now vagrant crashes when `vagrant destroy` is invoked (#455)

**Comment by hsoft** [comment] 2018-02-02 13:05
Oh, of course, the `sudoers` thing. That's an annoying problem that will fade when unprivileged containers are supported. I guess we can close this issue now that it became a duplicate of #455?

**Closed by hsoft** 2018-02-02 13:05 UTC

**Comment by thePanz** [comment] 2018-02-02 13:31
@hsoft ok for closing this.
But the issue only appeared after upgrading vagrant and vagrant-lxc plugin. Coudl it be related to the latest changes introduced in v1.3.0?

**Comment by hsoft** [comment] 2018-02-02 13:52
Yes it's because of my change for #406 which has more side effects than anticipated...

**Comment by hsoft** [comment] 2018-02-02 19:24
@ccope I'm thinking of removing that whole cleanup thing altogether. I've been testing things on `debian/stretch64` and it's *already* properly cleaning up files. I'm thinking that the problem described in #68 was a env-specific thing that should be handled in the guest, not by `vagrant-lxc` attempting to do so in a distro-agnostic manner. What's you're take on this?
