### ISSUE TITLE
Vagrant LXC fails with "undefined method `encode' for nil:NilClass (NoMethodError)" if container name is too long

### ISSUE THREAD

**Issue by tknerr** [fgrehm/vagrant-lxc#337] opened 2015-01-10 14:11 UTC
Hi!

I'm trying to get vagrant-lxc working on my [Ubuntu based dev-box](https://github.com/tknerr/dev-box/). So far everything works as expected.

However, when vagrant-lxc is used from within [test-kitchen](https://github.com/test-kitchen/test-kitchen) (a framework for integration testing chef cookbooks) I get weird errors like these:
```
tkn@dev-box:~/sample-toplevel-cookbook/.kitchen/kitchen-vagrant/kitchen-sample-toplevel-cookbook-default-ubuntu-12.04$ vagrant up
Bringing machine 'default' up with 'lxc' provider...
==> default: Importing base box 'fgrehm/precise64-lxc'...
==> default: Checking if box 'fgrehm/precise64-lxc' is up to date...
==> default: Starting container...
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:28:in `block in initialize': undefined method `encode' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:28:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:22:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:22:in `execute'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/sudo_wrapper.rb:73:in `block in raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/sudo_wrapper.rb:72:in `raw'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/sudo_wrapper.rb:39:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/sudo_wrapper.rb:37:in `execute'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/sudo_wrapper.rb:17:in `run'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/driver/cli.rb:160:in `run'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/driver/cli.rb:85:in `start'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/driver.rb:107:in `start'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/action/boot.rb:24:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/action/forward_ports.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/action/warn_networks.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/action/prepare_nfs_settings.rb:15:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/action/prepare_nfs_valid_ids.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:160:in `handle'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:42:in `block in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:41:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-cachier-1.1.0/lib/vagrant-cachier/action/install_buckets.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-omnibus-1.4.1/lib/vagrant-omnibus/action/install_chef.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-berkshelf-4.0.2/lib/vagrant-berkshelf/action/upload.rb:13:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-berkshelf-4.0.2/lib/vagrant-berkshelf/action/install.rb:10:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-berkshelf-4.0.2/lib/vagrant-berkshelf/action/save.rb:10:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-cachier-1.1.0/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/box_check_outdated.rb:68:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/action/create.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-lxc-1.0.1/lib/vagrant-lxc/action/handle_box_metadata.rb:41:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-toplevel-cookbooks-0.2.3/lib/vagrant-toplevel-cookbooks/action/clone.rb:124:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-berkshelf-4.0.2/lib/vagrant-berkshelf/action/share.rb:10:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-berkshelf-4.0.2/lib/vagrant-berkshelf/action/load.rb:10:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/tkn/.vagrant.d/gems/gems/vagrant-berkshelf-4.0.2/lib/vagrant-berkshelf/action/check.rb:12:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

Looking at the `/var/lib/lxc/` directory I can see a pretty long named config file for a moment:
```
root@dev-box:~# ll /var/lib/lxc/
total 16
drwx------  3 root root 4096 Jan 10 13:58 ./
drwxr-xr-x 70 root root 4096 Jan 10 12:46 ../
-rw-r--r--  1 root root  116 Jan 10 13:46 config
drwxrwx---  3 root root 4096 Jan 10 13:58 kitchen-sample-toplevel-cookbook-default-ubuntu-12.04_default_1420898335606_74946/
```

I'm pretty sure that this name is generated based on the directory of the Vagrantfile and that it is too long (this one is 81 chars) for LXC to handle.

At least I can get it to work if I shorten the directory name to 64 chars or less.

This was a pain to debug. It might happen to others too. Proposals:

 * warn the user and abort if the auto-generated container name is too long
 * warn the user and strip the auto-generated container name to 64 chars
 * other ideas?

**Comment by tknerr** [comment] 2015-01-10 14:13
P.S.: it works if I'm setting the container name explicitly

However:

 * this will probably be not unique anymore
 * I'm not sure how to pass this to the Vagrantfile that test-kitchen automatically generates

**Comment by tknerr** [comment] 2015-01-10 14:17
P.P.S: steps to reproduce (assuming vagrant-lxc is already set up):

```
git clone https://github.com/tknerr/sample-toplevel-cookbook.git
cd sample-toplevel-cookbook
bundle install
rake integration
```

**Comment by tknerr** [comment] 2015-01-10 20:57
I am currently working around it by explicitly setting the container_name in .kitchen.yml. 

However this required a patch for kitchen-vagrant so that it supports customization of the vagrant-lxc provider options. PR here:
https://github.com/test-kitchen/kitchen-vagrant/pull/128

Imho it would be better if the auto-generated container name would be automatically shortened and never exceed the 64 chars limit.

**Comment by fgrehm** [comment] 2015-01-11 15:27
Thanks for tracking it down, tagged it as a bug!

**Comment by fgrehm** [comment] 2015-01-11 23:31
Fixed in git! Thanks for tracking down the root cause :beers:

**Closed by fgrehm** 2015-01-11 23:31 UTC
Labels: bug

**Comment by tknerr** [comment] 2015-01-12 22:04
Sweet, thanks for fixing! :+1: :beers:
