### ISSUE TITLE
aa_allow_incomplete required on Ubuntu 14.10

### ISSUE THREAD

**Issue by bryanlarsen** [fgrehm/vagrant-lxc#333] opened 2014-12-20 20:25 UTC
I had to add this to my Vagrantfile to allow it to work with a Ubuntu 14.10 host

```
  config.vm.provider :lxc do |lxc|
    lxc.customize "aa_allow_incomplete", 1
  end
```

**Comment by onionjake** [comment] 2015-01-05 19:01
I also had to add that option on Ubuntu 14.10.

**Comment by fgrehm** [comment] 2015-01-12 00:38
Confirmed that this is an issue on Ubuntu 14.10. Does anyone know why is that needed?

**Comment by jvanoostveen** [comment] 2015-01-12 10:08
The change to the Vagrantfile is also breaking provisioning for < 14.10. Actually breaking LXC at a whole for the container (`lxc-ls` and friends will no longer work for the created container). Only solution to get to a sane state is removing the files from `/var/lxc/`...

**Comment by fgrehm** [comment] 2015-01-12 10:48
Looks like that config was introduced on lxc 1.1.0.alpha2: https://github.com/lxc/lxc/commit/7aff4f43fd84b021db12b2ffed1a4aa1b4cf65ef

Which lxc version have you guys got up there?

**Comment by fgrehm** [comment] 2015-01-12 10:49
Just to make things clear: @jvanoostveen that is kinda of expected because you are probably using a lxc version that does not support that config.

**Comment by jvanoostveen** [comment] 2015-01-12 12:24
That might be true, but it makes it hard to commit this line in the repository.

The version installed on my system is `1.1.0.alpha2`. It was required to even be able to run lxc as I can recall.

**Comment by fgrehm** [comment] 2015-01-12 12:49
Yup, I'm not planning to add any logic around this to the plugin since it is not required on pre 1.1.0 (which is what I believe most people are still using these days as it is what ships on 14.04 LTS)

Tagged this as a documentation change so it reminds me of adding instructions around this to the README.

**Comment by onionjake** [comment] 2015-01-12 15:47
I added a check for the LXC version to the `Vagrantfile` like so:

```ruby
LXC_VERSION = `lxc-ls --version`.strip
Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.provider :lxc do |lxc|
    if LXC_VERSION != '1.0.6'
      lxc.customize 'aa_allow_incomplete', '1'
    end
    lxc.customize 'network.mtu','1400'
  end
end
```

You could make the comparison a bit more intelligent, but this worked for what I needed.

**Comment by stucki** [comment] 2015-01-27 10:57
This seems to work:

```
    LXC_VERSION = `lxc-ls --version`.strip unless defined? LXC_VERSION
    if LXC_VERSION >= "1.1.0"
      # Allow start without AppArmor, otherwise Box will not Start on Ubuntu 14.10
      # see https://github.com/fgrehm/vagrant-lxc/issues/333
      lxc.customize 'aa_allow_incomplete', 1
    end
```

**Comment by fgrehm** [comment] 2015-03-03 02:52
Cool, and what you guys described can be easily added to the global `$HOME/.vagrant.d/Vagrantfile` ;-)

**Comment by stucki** [comment] 2015-03-03 13:56
Things like this should work out of the box don't you think?

**Comment by fgrehm** [comment] 2015-03-03 15:10
It might... I need some time to better understand what that flag is actually doing, in the meantime, lxc 1.1.0+ users can work around that by adding the following to `$HOME/.vagrant.d/Vagrantfile`:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider :lxc do |lxc|
    lxc.customize 'aa_allow_incomplete', 1
  end
end
```

**Comment by fgrehm** [comment] 2022-11-17 01:49
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:

**Closed by fgrehm** 2022-11-17 01:49 UTC
Labels: documentation, ignored
