### ISSUE TITLE
ctrl-c'ing the sudo prompt on vagrant up destroys the VM 

### ISSUE THREAD

**Issue by bryanlarsen** [fgrehm/vagrant-lxc#336] opened 2015-01-08 14:24 UTC
versions:
- vagrant 1.7.1
- vagrant-lxc 1.0.1
- ubuntu 14.10
- lxc 1.1.0.alpha2

To reproduce: 
- type `vagrant up` in a directory containing a vagrant-lxc VM
- at the sudo prompts, type 'ctrl-c' instead of entering a password
- hit ctrl-c to the _virtualbox_ provisioning process
- type `vagrant up --provider=lxc`
- watch vagrant-lxc provision a new VM instead of bringing up your old one

I suspect that it's possible to recover the VM at this stage.  The old VM still exists in `lxc-ls`, but you'd have to regenerate the lost metadata, like the private key.

**Comment by fgrehm** [comment] 2015-01-11 20:12
are you bringing up the vm from scratch or bringing it up after a `vagrant down`?

**Comment by bryanlarsen** [comment] 2015-01-11 20:24
Bringing it up after a down.

**Comment by tail** [comment] 2015-02-06 21:31
I just ran into the exact same issue.  Similar setup:

- vagrant 1.7.2
- vagrant-lxc 1.1.0
- ubuntu 14.10
- lxc 1.1.0-rc4

This seems to happen to me any time after I "ctrl-c" the sudo prompt.  In my case, I was trying to `vagrant ssh`.  Unfortunately since the private key gets wiped, here's what I did to get back into my original container:

- run `vagrant up --provider lxc` again to recreate the metadata
- copy the `.ssh/authorized_keys` from the newly spun up container into my original container (in `/var/lib/lxc`).
- run `vagrant halt`
- modify the `action_provision` and `id` files inside of `.vagrant` to point back to the original container's name
- run `lxc destroy --name <new container>` to remove the new container that was created

**Comment by bryanlarsen** [comment] 2015-03-03 14:07
Note that it just has to be a ctrl-c at an inopportune place, it doesn't have to be at a sudo prompt.   After my last misadventure, I ran vagrant lxc sudoers.   However this morning I killed my container by doing:

- vagrant up, successfully
- go get coffee
- vagrant up, again
- hit 'ctrl-c' immediately rather then letting it fail

**Comment by leorochael** [comment] 2015-04-01 21:56
Got a similar issue, in a setup similar to @tail.

I can't reliably reproduce the machine destruction on `vagrant up`, but if I do `vagrant up --no-provision` on one terminal window, wait for the machine to finish booting, then on a different terminal window (to avoid sudo credential caching by tty), I do `vagrant halt`, and type ctrl-c on both sudo prompts that are presented, then I get:

    ==> default: The container hasn't been created yet.

This means that `.vagrant/machines/default/lxc` directory is wiped clean, and Vagrant will create a new lxc container the next time.

The previous lxc-container keeps running and I need to stop and destroy it using lxc commands.

**Comment by tallysmartins** [comment] 2016-02-02 14:27
I got the same problem when cntr-c'ing when I typed vagrant ssh... with message ==> default: The container hasn't been created yet.

But if you type sudo lxc-ls you can see the old container is still there. What happens is that vagrant files that points to the old container are erased. The files stands in a hidden folder .vagrant/machines/default/lxc

You can just generate another container with vagrant up and then retrieve the old container pointing the files to the correct container name in lxc/id and lxc/action_provision files under the .vagrant folder

But you'll have to enter "vagrant" password since also you lost the private key. But you can generate another public key and then put it into the autoryzed_keys inside the container.

Sorry for the bad english
Att

**Comment by sjamaan** [comment] 2017-06-29 08:10
I believe this is a Vagrant issue in general. I've experienced these issues many many times with libvirt as well (before I even had the vagrant-lxc plugin installed). This happens a lot while developing a plugin or even just when there was a small mistake somewhere in my Vagrantfile.

Vagrant just tends to "lose" configured boxes whenever something fails. So I doubt this can be fixed in the LXC provider.

**Comment by ccope** [comment] 2017-12-13 06:09
This was a very annoying problem for me until I enabled the sudo wrapper. I think there's a good chance this is a bug in the vagrant-lxc provider. The relevant code is in the following functions:
https://github.com/fgrehm/vagrant-lxc/blob/10c53c54d76a2be9e3b3d766958993ffcc9098c1/lib/vagrant-lxc/provider.rb#L41
https://github.com/fgrehm/vagrant-lxc/blob/master/lib/vagrant-lxc/driver.rb#L32
(skipping a few layers of indirection here...)
https://github.com/fgrehm/vagrant-lxc/blob/master/lib/vagrant-lxc/sudo_wrapper.rb#L54

I think what happens is that the execute() function doesn't retry the command if it gets interrupted, so it returns empty stdout. Then, the list function gets empty output and assumes the machine is gone. execute() seems broken, I don't think it would ever make sense to continue processing stderr/stdout if the command was interrupted.

**Comment by nicobrevin** [comment] 2017-12-15 23:02
I have a fix for this, ill sort a pr...

**Comment by hsoft** [comment] 2018-02-18 13:53
Hey, this was fixed in #449. Closing.

**Closed by hsoft** 2018-02-18 13:53 UTC
Labels: bug
