### ISSUE TITLE
lxc container does not start because of share folders

### ISSUE THREAD

**Issue by xrmx** [fgrehm/vagrant-lxc#332] opened 2014-12-17 10:15 UTC
Am trying to convert a virtualbox Vagrantfile to lxc, it fails with share folders with:
      lxc-start 1418810383.099 ERROR    lxc_conf - No such file or directory - failed to mount '/src/foo/bar' on '/usr/lib/i386-linux-gnu/lxc/rootfs/home/vagrant/foo/libs/bar'

Config is:
    config.vm.share_folder "foo", "/home/vagrant/foo", "."
    config.vm.share_folder "bar", "/home/vagrant/foo/libs/bar, "../bar/"

The Vagrantfile is in /src/foo/foo and tree is like this:
/src/foo/foo
/src/foo/foo/libs
/src/foo/bar

This is a debian sid with lxc is 1.0.6 and vagrant 1.6.5.
Any hint on what could be wrong?

**Comment by xrmx** [comment] 2015-01-12 10:14
If i'll comment these lines it'll fail with:
There was an error executing ["sudo", "lxc-attach", "--name", "odin_default_1421057506055_89332", "--namespaces", "NETWORK|MOUNT", "--", "/sbin/ip", "-4", "addr", "show", "scope", "global", "eth0"]

**Comment by fgrehm** [comment] 2015-01-12 10:44
That sucks :-( I don't have a pre configured sid VM around to try this out but I'll try to have a look at this before the 1.1.0 release

**Comment by Jbonnett** [comment] 2015-02-10 18:17
I am seeing a similar error, its failing for me because i dont have eth0. I am using device names like enp0s25 Perhaps xrmx can run ifconfig and confirm on his end? 
(P.S. this is all caused by the perhaps poorly named  http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/)

**Comment by xrmx** [comment] 2015-02-11 09:10
@Jbonnett i have eth0, wlan0 and lo interfaces on my host

**Comment by Jbonnett** [comment] 2015-02-11 19:34
Hrmm. the plot thickens. I was able to get up and running on my machine, but I need to do some a/b testing to find the change that fixed this error message.

**Comment by Ramblurr** [comment] 2015-02-25 15:19
Is the title of this bug still the topic?

When I have share_folder lines in my Vagrantfile, I get LXC log entries:

```
      lxc-start 1424874792.098 ERROR    lxc_conf - conf.c:mount_entry:2049 - No such device - failed to mount '/home/ramblurr/src/vendor/VVV.lxc/www' on '/usr/lib64/lxc/rootfs/srv/www'
      lxc-start 1424874792.098 ERROR    lxc_conf - conf.c:lxc_setup:4163 - failed to setup the mount entries for 'VVVlxc_default_1424874785476_46564'
      lxc-start 1424874792.098 ERROR    lxc_start - start.c:do_start:688 - failed to setup the container
```

Then vagrant hangs running lxc-ls in a loop waiting for the machine too boot, but it doesn't.

Any tips on getting shared folders working?

**Comment by dstelter** [comment] 2015-03-10 16:30
In my case it was caused by existing mount_options in the the Vagrantfile. Appending the "bind" option resolved the issue.
I would suggest to modify share_folder in vagrant-lxc/driver.rb to augment existing mount_options with bind if the guest path is not a block device.

**Comment by Snkz** [comment] 2015-03-25 14:28
@dstelter Could you elaborate? What bind option?

**Comment by dstelter** [comment] 2015-03-26 18:54
In order to remount existing folders in a second location the bind option is needed (see http://linux.die.net/man/8/mount). Vagrant-lxc passes this flag by default, but if you specify custom mount_options this gets overwritten (see https://github.com/fgrehm/vagrant-lxc/blob/master/lib/vagrant-lxc/driver.rb#L107). It should be sufficient to modify your Vagrantfile accordingly (e.g. "dmode=0775,fmode=775,bind").

**Comment by mwild1** [comment] 2016-05-19 12:52
Confirmed - I had the same problem, thanks for the tip! I am trying to get a Vagrantfile that someone wrote for a project to work on my system under lxc. They had:

`config.vm.synced_folder ".", "/vagrant", :mount_options => ["ro"]`

This produced the following line in the generated lxc config:

`lxc.mount.entry=/home/path/to/dir vagrant none ro 0 0`

But removing the `:mount_options` from Vagrantfile generated a line like this:

`lxc.mount.entry=/home/path/to/dir vagrant none bind,create=dir 0 0`

Maybe vagrant-lxc should always append `bind` and `create=dir` to the specified mount options if they are not present?

**Comment by ccope** [comment] 2016-05-20 07:24
Maybe, except there is also create=file, so it'll have to check for that.

**Comment by fgrehm** [comment] 2022-11-17 01:49
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:

**Closed by fgrehm** 2022-11-17 01:49 UTC
Labels: needs info, ignored
