### ISSUE TITLE
vagrant-lxc-wrapper doesn't allow 'rm' on Fedora

### ISSUE THREAD

**Issue by detached** [fgrehm/vagrant-lxc#323] opened 2014-10-21 09:17 UTC
sudoers rm is /bin/rm on Fedora20

vagrant-lxc-wrapper has only /usr/bin/rm whitelisted

that results in the error:

```
There was an error executing ["sudo", "/usr/local/bin/vagrant-lxc-wrapper", "rm", "/usr/share/lxc/templates/lxc-vagrant-tmp-lxc_default_1413883001571_41712"]
```

**Comment by kupferk** [comment] 2015-01-09 14:32
I also have a similar problem on Fedora 21, but found a workaround. Let me describe what happens.

1. As a normal user, I run "vagrant lxc sudoers"
In this case the sudo_wrapper file gets created and has whitelist entries which begin with "/usr/bin/..."
This is consistent with

> env | grep PATH
> PATH=/home/kaya/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/bin

But then I receive the error "lxc package not installed" when trying to start my box:
> vagrant up --provider=lxc
> The `lxc` package does not seem to be installed or is not accessible on the PATH.

When I turn on debugging, I can see that vagrant is actually try to execute /bin/whch instead of /usr/bin/which
And this behaviour is the root cause of my problem. When I execute a command without sudo, I get a different search PATH than with sudo:

> env | grep PATH
> PATH=/home/kaya/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:
/usr/sbin:/bin:/sbin:/bin

as opposed to

> sudo env | grep PATH
> PATH=/sbin:/bin:/usr/sbin:/usr/bin

Note that the order of entries is also different!

I could workaround this problem by also using sudo for generating the sudoer wrapper script

> sudo vagrant lxc sudoers

This will generate a correct sudo wrapper script.

**Comment by fgrehm** [comment] 2015-01-11 15:17
This is very weird and I'll need to reproduce this locally to help you out.

How are you setting up your Fedora host? Are you using the instructions from https://github.com/fgrehm/vagrant-lxc/wiki/Usage-on-fedora-hosts?

**Comment by kupferk** [comment] 2015-01-12 08:39
I setup my fedora host using Method 2 from the instructions. Other than that maybe there might be something wrong, because I started using Fedora 16 on my machine and upgraded to Fedora 21 during the last years. So maybe my machine has a slightly different configuration than a fresh install of Fedora 21.

**Comment by fgrehm** [comment] 2015-01-12 10:49
I'll try reproducing this on a clean VBox VM before 1.1.0

**Comment by kupferk** [comment] 2015-01-29 08:13
This seems to work now with 1.1.0. Thanks a lot!

**Comment by Ramblurr** [comment] 2015-02-25 15:21
This issue reared its head again for me on Fedora 21 using 1.1.0 (installed from the new rpm packages).

I outlined it in #350 , but I'll repeat:

On Fedora the root has a different PATH than my user.

As root (when I run sudo vagrant lxc sudoers) /bin is first in the PATH, whereas when I run vagrant as my user /usr/bin is first. This results in a wrapper file that uses an lxc_bin of /bin, but the vagrant user is passing in /usr/bin/ as a path.

**Comment by fgrehm** [comment] 2022-11-17 01:49
Hey, sorry for the silence here but this project is looking for maintainers :sweat_smile: 

As per https://github.com/fgrehm/vagrant-lxc/issues/499, I've added the `ignored` label and will close this issue. Thanks for the interest in the project and LMK if you want to step up and take ownership of this project on that other issue :wave:

**Closed by fgrehm** 2022-11-17 01:49 UTC
Labels: bug, ignored
